codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0
        if_ci_failed: error
    patch:
      default:
        target: auto
        threshold: 0
        if_ci_failed: error
