<?php

/**
 * @file
 * Hook implementations for the Webform OpenFisca module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_webform_third_party_settings_form_alter().
 */
function webform_openfisca_webform_third_party_settings_form_alter(array &$form, FormStateInterface $form_state) : void {
  /** @var \Drupal\webform_openfisca\WebformThirdPartySettingsFormAlter $alter_service */
  $alter_service = \Drupal::service('webform_openfisca.webform_form_alter.third_party_settings');
  $alter_service->alterForm($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter() for webform_ui_element_form.
 */
function webform_openfisca_form_webform_ui_element_form_alter(array &$form, FormStateInterface $form_state, string $form_id) : void {
  /** @var \Drupal\webform_openfisca\WebformUiElementFormAlter $alter_service */
  $alter_service = \Drupal::service('webform_openfisca.webform_form_alter.ui_element');
  $alter_service->alterForm($form, $form_state);
}

/**
 * Implements hook_help().
 */
function webform_openfisca_help(string $route_name, RouteMatchInterface $route_match) : string {
  if ($route_name === 'help.page.webform_openfisca') {
    $token_tree = \Drupal::service('token.tree_builder')->buildRenderable(['webform_openfisca'], [
      'click_insert' => FALSE,
      'show_restricted' => TRUE,
      'show_nested' => TRUE,
      'global_types' => FALSE,
    ]);
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The <a href=":project">Webform OpenFisca Integration</a> module integrates Drupal Webform functionality with the OpenFisca API, allowing for seamless communication and calculation based on OpenFisca rules.', [':project' => 'https://www.drupal.org/project/webform_openfisca']) . '</p>';
    $output .= '<dl>';
    $output .= '<dt>' . t('The list of the currently available tokens provided by this module are shown below.') . '</dt>';
    $output .= '<dd>' . \Drupal::service('renderer')->render($token_tree) . '</dd>';
    $output .= '</dl>';
    return $output;
  }
  // @codeCoverageIgnoreStart
  return '';
  // @codeCoverageIgnoreEnd
}

/**
 * Implements hook_preprocess_block();
 */
function webform_openfisca_preprocess_block(array &$variables): void {
  // Get the block ID.
  $block_id = $variables['elements']['#id'] ?? NULL;
  /** @var \Drupal\Core\Entity\Block $block */
  $block = \Drupal::entityTypeManager()->getStorage('block')->load($block_id);
  if ($block instanceof \Drupal\block\BlockInterface && str_starts_with($block->getPluginId(), 'block_content')) {
    $uuid = explode(':', $block->getPluginId());
    $block_content = \Drupal::entityTypeManager()->getStorage('block_content')->loadByProperties(['uuid' => $uuid[1]]);
    $block_content = reset($block_content);

    // Get current path or query parameters
    $query = \Drupal::request()->query->all();

    // Example: check if 'blocks' is in query parameters
    $current_block_id = $query['blocks'] ?? NULL;
    $current_block_ids = explode(',', $current_block_id);

    if ($block_content->bundle() == 'civictheme_component_block') {
      if (!$block_content->id()) {
        return;
      }

      // Only render block if its ID matches the current URL
      if (!in_array($block_content->id(), $current_block_ids)) {
        $variables['content'] = [];
      }
    }
  }
}