<?php

/**
 * @file
 * Hooks implemented by the webform_openfisca module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_webform_third_party_settings_form_alter().
 */
function webform_openfisca_webform_third_party_settings_form_alter(&$form, FormStateInterface $form_state) : void {
  /** @var \Drupal\webform_openfisca\WebformThirdPartySettingsFormAlter $alter_service */
  $alter_service = \Drupal::service('webform_openfisca.webform_form_alter.third_party_settings');
  $alter_service->alterForm($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter() for webform_ui_element_form.
 */
function webform_openfisca_form_webform_ui_element_form_alter(&$form, FormStateInterface $form_state, $form_id) : void {
  /** @var \Drupal\webform_openfisca\WebformUiElementFormAlter $alter_service */
  $alter_service = \Drupal::service('webform_openfisca.webform_form_alter.ui_element');
  $alter_service->alterForm($form, $form_state);
}

/**
 * Implements hook_help().
 */
function webform_openfisca_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name === 'help.page.webform_openfisca') {
    $token_tree = \Drupal::service('token.tree_builder')->buildRenderable(['webform_openfisca'], [
      'click_insert' => FALSE,
      'show_restricted' => TRUE,
      'show_nested' => FALSE,
      'global_types' => FALSE,
    ]);
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The <a href=":project">Webform OpenFisca Integration</a> module integrates Drupal Webform functionality with the OpenFisca API, allowing for seamless communication and calculation based on OpenFisca rules.', [':project' => 'https://www.drupal.org/project/webform_openfisca']) . '</p>';
    $output .= '<dl>';
    $output .= '<dt>' . t('The list of the currently available tokens provided by this module are shown below.') . '</dt>';
    $output .= '<dd>' . \Drupal::service('renderer')->render($token_tree) . '</dd>';
    $output .= '</dl>';
    return $output;
  }
}
